"use strict";
let placesTovisit = ["Pakistan", "America", "Italy", "France", "Norway"];
console.log("Orginal Order", placesTovisit);
console.log("Alphabetical Order", [...placesTovisit].sort());
console.log("Orginal Order", placesTovisit);
console.log("Reverse Alphabetical Order", [...placesTovisit].sort().reverse());
console.log("Orginal Order", placesTovisit);
console.log("Reversed Order", placesTovisit.reverse());
console.log("Back to its Original Order", placesTovisit.reverse());
console.log("Sorted in Aplhabetical Order", placesTovisit.sort());
console.log("Sorted in Reverse Aplhabetical Order", placesTovisit.sort().reverse());
