"use strict";
let name_1 = "Car";
let name_2 = "car";
console.log(name_1 === name_2);
console.log(name_1 !== name_2);
let word = "HelloWorld";
console.log(word.toLowerCase() === "HelloWorld");
console.log(word.toLowerCase() === "helloworld");
const num1 = 10;
const num2 = 40;
console.log(num1 === num2);
console.log(num1 !== num2);
console.log(num1 < num2);
console.log(num1 <= num2);
console.log(num1 > num2);
console.log(num1 >= num2);
let cond1 = true;
let cond2 = false;
console.log(cond1 && cond2);
console.log(cond1 || cond2);
const cars = ["Lamborghini", "BMW", "Ferrari", "Porsche"];
console.log(cars.includes("Lamborghini"));
console.log(cars.includes("lamborghini"));
